name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Build Release
      run: cargo build --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LoLCountermatcher-Windows-Rust-Exe
        path: target/release/lol_countermatcher.exe

    - name: Create Release and Upload Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/lol_countermatcher.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
